agents:
  queue: 'opensource'

steps:

  - label: ':android: Build Fixtures'
    key: "fixtures"
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    artifact_paths:
      - "build/test-fixture.apk"
      - "build/android_fixture_url.txt"
      - "build/android_bs_fixture_url.txt"
      - "build/test-fixture.ipa"
      - "build/ipa_url_bb_release.txt"
      - "build/ipa_url_bs_release.txt"
      - "build/web.zip"
      - "build/fixture/*"
    commands:
      - bundle install
      - make test-fixture
      - bundle exec upload-app --farm=bb --app=./build/test-fixture.apk --app-id-file=build/android_fixture_url.txt
      - bundle exec upload-app --farm=bs --app=./build/test-fixture.apk --app-id-file=build/android_bs_fixture_url.txt
      - bundle exec upload-app --farm=bb --app=./build/test-fixture.ipa --app-id-file=build/ipa_url_bb_release.txt
      - bundle exec upload-app --farm=bs --app=./build/test-fixture.ipa --app-id-file=build/ipa_url_bs_release.txt
    env:
      JAVA_VERSION: 17

  - label: ':android: Coding standards checks'
    timeout_in_minutes: 20
    agents:
      queue: macos-14
    command: './gradlew --continue detekt ktlintCheck'
    env:
      JAVA_VERSION: 17

  - label: ':android: Lint mazerunner scenarios'
    timeout_in_minutes: 10
    agents:
      queue: macos-14
    commands:
      - make install
      - cd features/fixtures/mazerunner
      - ./gradlew ktlintCheck detekt
    env:
      JAVA_VERSION: 17

  - label: ':bitbar: Android 15 end-to-end tests'
    depends_on: "fixtures"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/test-fixture.apk"
          - "build/android_fixture_url.txt"
          - "build/android_bs_fixture_url.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        service-ports: true
        command:
          - "features/common"
          - "--app=@build/android_fixture_url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_15"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
